/*
 * Author: Anurag Tripathi
 * Description: application wide constant are defined here
 * Date: May 25, 2021
 */
module.exports = {
  USER_MOOD: {
    TYPE: {
      ARTIST: 1,
      PLAYLIST: 2,
      TRACK: 3,
      ALBUM: 4,
    },
    VENDOR: {
      SPOTIFY: 1,
      APPLE: 2,
    },
    ACTION: {
      LIKE: 0,
      DISLIKE: 1,
      SUPERLIKE: 2,
    },
  },
  GENRE_MAP: {
    "ALT-ROCK": 'rock',
    "ALTERNATIVE": 'rock',
    "BLACK-METAL": 'rock',
    "BLUEGRASS": 'rock',
    "BLUES": 'rock',
    "COUNTRY": 'rock',
    "DEATH-METAL": 'rock',
    "EMO": 'rock',
    "GOTH": 'rock',
    "GRINDCORE": 'rock',
    "GRUNGE": 'rock',
    "GUITAR": 'rock',
    "HARD-ROCK": 'rock',
    "HARDSTYLE": 'rock',
    "HEAVY-METAL": 'rock',
    "J-ROCK": 'rock',
    "METAL": 'rock',
    "METAL-MISC": 'rock',
    "METALCORE": 'rock',
    "PSYCH-ROCK": 'rock',
    "PUNK": 'rock',
    "PUNK-ROCK": 'rock',
    "ROCK": 'rock',
    "ROCK-N-ROLL": 'rock',
    "ROCKABILLY": 'rock',
    "SKA": 'rock',
    "ACOUSTIC": 'pop',
    "AMBIENT": 'pop',
    "CANTOPOP": 'pop',
    "CHILL": 'pop',
    "DISNEY": 'pop',
    "GROOVE": 'pop',
    "INDIE-POP": 'pop',
    "INDIE": 'pop',
    "J-POP": 'pop',
    "K-POP": 'pop',
    "KIDS": 'pop',
    "LATIN": 'pop',
    "LATINO": 'pop',
    "MANDOPOP": 'pop',
    "POP": 'pop',
    "POP-FILM": 'pop',
    "POWER-POP": 'pop',
    "REGGAE": 'pop',
    "SALSA": 'pop',
    "SAMBA": 'pop',
    "SOUL": 'pop',
    "SYNTH-POP": 'pop',
    "SERTANEJO": 'pop',
    "AFROBEAT": 'rap',
    "HIP-HOP": 'rap',
    "R-N-B": 'rap',
    "REGGAETON": 'rap',
    "TRIP-HOP": 'rap',
    "CLASSICAL": 'classical',
    "FOLK": 'classical',
    "FORRO": 'classical',
    "GOSPEL": 'classical',
    "JAZZ": 'classical',
    "MOVIES": 'classical',
    "OPERA": 'classical',
    "PIANO": 'classical',
    "SOUNDTRACKS": 'classical',
    "TANGO": 'classical',
    "MPB": 'classical',
    "CHICAGO-HOUSE": 'electronic',
    "CLUB": 'electronic',
    "DANCE": 'electronic',
    "DANCEHALL": 'electronic',
    "DEEP-HOUSE": 'electronic',
    "DETROIT-TECHNO": 'electronic',
    "DISCO": 'electronic',
    "DRUM-AND-BASS": 'electronic',
    "DUB": 'electronic',
    "DUBSTEP": 'electronic',
    "EDM": 'electronic',
    "ELECTRO": 'electronic',
    "ELECTRONIC": 'electronic',
    "FUNK": 'electronic',
    "GARAGE": 'electronic',
    "HOUSE": 'electronic',
    "J-DANCE": 'electronic',
    "MINIMAL-TECHNO": 'electronic',
    "PARTY": 'electronic',
    "POST-DUBSTEP": 'electronic',
    "PROGRESSIVE-HOUSE": 'electronic',
    "TECHNO": 'electronic',
    "TRANCE": 'electronic',
    "NEW-AGE": 'electronic',
    "IDM": 'electronic'
    }
};
