-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIKWjESpucEzHzrGLkk9+JwEcVaADTsX88/ZoXHEY4GD8oAoGCCqGSM49
AwEHoUQDQgAEkWpUryp39vp+0tvaUKNvFIOuqW32F9llFkMdSBn/RvEXmtaOL3QR
p1rhQKL3dq6eHW4NjBoOUseRG3dcbugJzQ==
-----END EC PRIVATE KEY-----
